apiVersion: v1
kind: Secret
metadata:
  name: travelmap-tester-postgresql
stringData:
  postgresql-info.yaml: |
    driver-class-name: "org.postgresql.Driver"
    url: "jdbc:postgresql://postgresql:5431"
    username: "prod"
    password: "prod123"