apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  part-of: k8s-anotherclass
  component: backend-server
  name: travelmap
  instance: travelmap-ins
  managed-by: kustomize
resources:
  - configmap.yaml
  - deployment.yaml
  - secret.yaml
  - service.yaml